// components/GuideModal/Page2.jsx
import React from 'react';
import h4hExampleOutput from '../../assets/h2hexampleoutput.png';

const Page2 = () => {
  return (
    <div>
      {/* Title */}
      <h2 
        className="mb-5"
        style={{
          width: '184px',
          height: '12px',
          color: '#000',
          fontFamily: 'Inter',
          fontSize: '13px',
          fontWeight: 700,
          lineHeight: 'normal'
        }}
      >
        Understanding the AI Output
      </h2>

      {/* Purple subtitle box */}
      <div 
        className="mb-3 flex items-center justify-center"
        style={{
          width: '159px',
          height: '27px',
          borderRadius: '12px',
          background: '#746BFF'
        }}
      >
        <span
          style={{
            color: '#F6F6F6',
            fontFamily: 'Inter',
            fontSize: '12px',
            fontWeight: 500,
            lineHeight: 'normal'
          }}
        >
          What will you be seeing?
        </span>
      </div>

      {/* Example output image */}
      <div className="mb-3">
        <img 
          src={h4hExampleOutput}
          alt="h4h example output"
          style={{
            width: '238px',
            height: '76px',
            aspectRatio: '119/38',
            borderRadius: '8px',
            border: '1px solid #DFDFDF',
            objectFit: 'cover'
          }}
        />
      </div>

      {/* Description text */}
      <div
        style={{
          color: '#000',
          fontFamily: 'Inter',
          fontSize: '9px',
          fontWeight: 400,
          lineHeight: '12px',
          textAlign: 'justify'
        }}
      >
        <p className="mb-2">
          You will be seeing outputs or answers like above. But you have 5 questions to use in this session for using this h4h system.
        </p>
        <p className="mb-2">
          The answers are generated by an AI, like ChatGPT, Claude, Gemini, or other AIs that you usually use.
        </p>
        <p>
          But, here is the thing, some parts may <strong>be more certain</strong> than others. To help you understand this, we add <strong>uncertainty markers</strong> directly inside the answer.
        </p>
      </div>
    </div>
  );
};

export default Page2;