// components/GuideModal.jsx
import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import logoShort from '../assets/logo-short.png';

const guidePages = [
  {
    id: 1,
    title: "Quick Guide to h4h",
    content: {
      heading: "How this project works?",
      description: "Human4Human helps you explore how AI expresses uncertainty in its responses. We add confidence markers to AI-generated answers, showing you which parts are more or less certain.",
      steps: [
        {
          number: 1,
          title: "Ask 5 Questions",
          description: "You have 5 question quotas about any topic"
        },
        {
          number: 2,
          title: "Read Marked Answers",
          description: "See uncertainty levels"
        },
        {
          number: 3,
          title: "Share Your Feedback",
          description: "Help improve AI transparency"
        }
      ]
    }
  },
  {
    id: 2,
    title: "Understanding the AI Output",
    subtitle: "What will you be seeing?",
    content: {
      description: "You will be seeing outputs or answers like above. But you only have limited up to 5 quotas or 5 questions for using this h4h system.",
      detail: "The answers are generated by an AI, like ChatGPT, Claude, Gemini, or other AI that you usually use.",
      highlight: "But, here is the thing, some parts may be more certain than others. To help you understand this, we add uncertainty markers directly inside the answer."
    }
  },
  {
    id: 3,
    title: "💚💛 Uncertainty Markers",
    subtitle: "Example:",
    content: {
      example: "Jakarta is the capital of Indonesia [verified, p=0.95]¹ ← RED (low confidence)",
      description: "Colors = Confidence level!",
      note: "Colors + Confidence level"
    }
  },
  {
    id: 4,
    title: "Color System",
    content: {
      colors: [
        {
          color: "GREEN",
          range: "High Confidence (0.8 - 1.0)",
          markers: ["verified", "factual", "likely"],
          meaning: ["Strong evidence supporting this", "You can trust this information", "Safe to rely on"]
        },
        {
          color: "RED",
          range: "Low Confidence (0 - 0.49)",
          markers: ["unsupported", "speculative", "contradicted"],
          meaning: ["Weak or conflicting evidence", "Be very skeptical", "Do NOT rely on this"]
        }
      ]
    }
  },
  {
    id: 5,
    title: "Understanding the P-Score",
    subtitle: "What does p=0.85 mean?",
    content: {
      description: "The p-score (probability) shows the AI's confidence level:",
      examples: [
        "p=0.95 → 95% confident (very reliable)",
        "p=0.68 → 68% confident (moderately reliable)",
        "p=0.45 → 45% confident (unreliable)"
      ],
      note: "Higher number = More reliable",
      footnote: {
        title: "Reading the Footnotes",
        description: "Each marker has a number like this: [marker]¹",
        details: [
          "The footnote tells you:",
          "Prediction type (SUPPORTS/REFUTES/NOT ENOUGH INFO)",
          "Confidence score (exact percentage)",
          "Uncertainty type (evidential or epistemic)",
          "Explanation why this confidence level"
        ]
      }
    }
  },
  {
    id: 6,
    title: "How to Use This",
    content: {
      dos: [
        "Check marker colors before trusting information",
        "Read footnotes for important decisions",
        "Be extra careful with red markers",
        "Use this as one tool among many"
      ],
      donts: [
        "Trust low confidence (red) information",
        "Ignore markers for critical decisions",
        "Assume green = 100% perfect",
        "Use this as your only source"
      ]
    }
  }
];

export const GuideModal = ({ isOpen, onClose, startPage = 0 }) => {
  const [currentPage, setCurrentPage] = useState(startPage);

  const nextPage = () => {
    if (currentPage < guidePages.length - 1) {
      setCurrentPage(currentPage + 1);
    } else {
      onClose();
    }
  };

  const prevPage = () => {
    if (currentPage > 0) {
      setCurrentPage(currentPage - 1);
    }
  };

  if (!isOpen) return null;

  const page = guidePages[currentPage];

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
        onClick={onClose}
      >
        <motion.div
          initial={{ scale: 0.9, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          exit={{ scale: 0.9, opacity: 0 }}
          onClick={(e) => e.stopPropagation()}
          className="relative bg-white rounded-2xl shadow-2xl overflow-hidden"
          style={{
            width: '390px',
            maxHeight: '600px',
            border: '1px solid #E0E0E0'
          }}
        >
          {/* Close button */}
          <button
            onClick={onClose}
            className="absolute top-4 right-4 z-10 w-8 h-8 flex items-center justify-center text-gray-600 hover:text-gray-900 bg-white rounded-full shadow-md"
          >
            ✕
          </button>

          {/* Content */}
          <div className="overflow-y-auto h-full p-8" style={{ maxHeight: '600px' }}>
            {/* Logo for first page */}
            {currentPage === 0 && (
              <div className="flex justify-center mb-6">
                <img src={logoShort} alt="h4h" className="w-20 h-20" />
              </div>
            )}

            {/* Page content */}
            <GuidePageContent page={page} />

            {/* Progress indicator */}
            <div className="flex justify-center gap-2 mt-8 mb-4">
              {guidePages.map((_, idx) => (
                <div
                  key={idx}
                  className={`h-1 rounded-full transition-all ${
                    idx === currentPage 
                      ? 'w-8 bg-purple-600' 
                      : 'w-2 bg-gray-300'
                  }`}
                />
              ))}
            </div>

            {/* Navigation */}
            <div className="flex justify-between items-center mt-6">
              <button
                onClick={prevPage}
                disabled={currentPage === 0}
                className="flex items-center gap-2 text-gray-600 disabled:opacity-30"
                style={{ visibility: currentPage === 0 ? 'hidden' : 'visible' }}
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="7" height="12" viewBox="0 0 7 12" fill="none">
                  <path d="M5.53027 11.4697L0.530273 6.46967L5.53027 1.46967" stroke="currentColor" strokeWidth="1.5"/>
                </svg>
                <span style={{ fontSize: '12px' }}>Back</span>
              </button>

              <span style={{ fontSize: '11px', color: 'rgba(0,0,0,0.5)' }}>
                page {currentPage + 1} out of {guidePages.length}
              </span>

              <button
                onClick={nextPage}
                className="flex items-center gap-2"
                style={{
                  padding: '8px 16px',
                  borderRadius: '8px',
                  background: 'linear-gradient(90deg, #57EFBD 25%, #77DBD9 37.5%, #96C8F4 50%, #BCB9F3 75%, #E2A9F1 100%)',
                  color: 'white',
                  fontSize: '12px',
                  fontWeight: 600
                }}
              >
                {currentPage === guidePages.length - 1 ? "Start" : "Next"}
                <svg xmlns="http://www.w3.org/2000/svg" width="7" height="12" viewBox="0 0 7 12" fill="none">
                  <path d="M0.530273 0.530327L5.53027 5.53033L0.530273 10.5303" stroke="white" strokeWidth="1.5"/>
                </svg>
              </button>
            </div>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
};

// Helper component to render page content
const GuidePageContent = ({ page }) => {
  return (
    <div style={{ fontFamily: 'Inter' }}>
      <h2 
        className="text-lg font-bold mb-2"
        style={{ color: page.title.includes('💚💛') ? '#000' : '#000' }}
      >
        {page.title}
      </h2>
      
      {page.subtitle && (
        <p className="text-sm text-blue-600 font-semibold mb-4">
          {page.subtitle}
        </p>
      )}

      {/* Render different content types based on page */}
      {page.id === 1 && (
        <div>
          <h3 className="font-semibold mb-2">{page.content.heading}</h3>
          <p className="text-sm text-gray-600 mb-4">{page.content.description}</p>
          <div className="space-y-3">
            {page.content.steps.map((step) => (
              <div key={step.number} className="flex items-start gap-3">
                <div className="w-8 h-8 rounded-full bg-purple-100 flex items-center justify-center flex-shrink-0">
                  <span className="text-purple-600 font-semibold text-sm">{step.number}</span>
                </div>
                <div>
                  <p className="font-semibold text-sm">{step.title}</p>
                  <p className="text-xs text-gray-600">{step.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {page.id === 2 && (
        <div className="text-sm space-y-3">
          <p className="text-gray-700">{page.content.description}</p>
          <p className="text-gray-700">{page.content.detail}</p>
          <div className="bg-purple-50 p-3 rounded-lg">
            <p className="text-gray-800">{page.content.highlight}</p>
          </div>
        </div>
      )}

      {page.id === 3 && (
        <div className="text-sm space-y-3">
          <div className="bg-gray-100 p-3 rounded-lg">
            <p className="font-mono text-xs">{page.content.example}</p>
          </div>
          <p className="font-semibold">{page.content.description}</p>
          <p className="text-gray-600 text-xs">{page.content.note}</p>
        </div>
      )}

      {page.id === 4 && (
        <div className="space-y-4">
          {page.content.colors.map((colorInfo, idx) => (
            <div key={idx} className="border rounded-lg p-3">
              <p className="font-semibold text-sm mb-1">
                {colorInfo.color === 'GREEN' ? '🟢' : '🔴'} {colorInfo.color}
              </p>
              <p className="text-xs text-gray-600 mb-2">{colorInfo.range}</p>
              <p className="text-xs mb-1">Markers: {colorInfo.markers.join(', ')}</p>
              <ul className="text-xs text-gray-600 space-y-1">
                {colorInfo.meaning.map((m, i) => (
                  <li key={i}>• {m}</li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      )}

      {page.id === 5 && (
        <div className="space-y-3 text-sm">
          <p className="text-gray-700">{page.content.description}</p>
          <ul className="space-y-1">
            {page.content.examples.map((ex, i) => (
              <li key={i} className="text-xs bg-gray-50 p-2 rounded">{ex}</li>
            ))}
          </ul>
          <p className="font-semibold text-center">{page.content.note}</p>
          <div className="border-t pt-3 mt-4">
            <p className="font-semibold mb-2">{page.content.footnote.title}</p>
            <p className="text-xs mb-2">{page.content.footnote.description}</p>
            <ul className="text-xs text-gray-600 space-y-1">
              {page.content.footnote.details.map((d, i) => (
                <li key={i}>• {d}</li>
              ))}
            </ul>
          </div>
        </div>
      )}

      {page.id === 6 && (
        <div className="space-y-4">
          <div>
            <p className="font-semibold mb-2 text-green-600">Do:</p>
            <ul className="text-xs space-y-1">
              {page.content.dos.map((item, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span>✓</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
          <div>
            <p className="font-semibold mb-2 text-red-600">Don't:</p>
            <ul className="text-xs space-y-1">
              {page.content.donts.map((item, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span>✗</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      )}
    </div>
  );
};